#
# Run desired Seismic sub-analysis
#

# Use iydt/seismic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and seismic-specific
# functions
FROM iydt/seismic

## source run file
CMD Rscript /I-SUGAR-hob/runMPEM.r > /I-SUGAR-hob/runMPEM.out
