#
# Run desired Crater sub-analysis
#

# Use iydt/crater image containing required
# R packages, global functions, IYDT-specific
# functions and data, and crater-specific
# functions
FROM iydt/crater

## source run file
CMD Rscript /I-SUGAR/runMPEM.r > /I-SUGAR/runMPEM.out
