#
# Run new event Crater inference
#

# Use iydt/crater image containing required
# R packages, global functions, IYDT-specific
# functions and data, and crater-specific
# functions
FROM iydt/crater

## source run file
CMD Rscript /I-SUGAR-0/runMPEM_0.r > /I-SUGAR-0/runMPEM_0.out
