#
# Run desired Optical sub-analysis
#

# Use iydt/optic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and optical-specific
# functions
FROM iydt/optic

## source run file
CMD Rscript /I-EIV/runMPEM.r > /I-EIV/runMPEM.out
