#
# Run calibration 3-Phen inference
#

# Use iydt/3-phen image containing required
# R packages, global functions, IYDT-specific
# functions and data, and phenomenology-specific
# functions
FROM iydt/3-phen

## source run file
CMD Rscript /3phen_eiv_cal/runMPEM.r > /I-EIV-SUGAR-hob-0/runMPEM.out
