#
# Run desired 3-Phen sub-analysis
#

# Use iydt/3-phen image containing required
# R packages, global functions, IYDT-specific
# functions and data, and phenomenology-specific
# functions
FROM iydt/3-phen

## source run file
CMD Rscript /I-EIV/runMPEM.r > /I-EIV/runMPEM.out
