#
# Run desired 4-Phen sub-analysis
#

# Use iydt/4-phen image containing required
# R packages, global functions, IYDT-specific
# functions and data, and phenomenology-specific
# functions
FROM iydt/4-phen

## source run file
CMD Rscript /I-EIV-SUGAR-hob/runMPEM.r > /I-EIV-SUGAR-hob/runMPEM.out
