#
# Run desired Acoustic sub-analysis
#

# Use iydt/acoustic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and acoustic-specific
# functions
FROM iydt/acoustic

## source run file
CMD Rscript /I/runMPEM.r > /I/runMPEM.out
