#
# Run calibration Seismic inference
#

# Use iydt/seismic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and seismic-specific
# functions
FROM iydt/seismic

## source run file
CMD Rscript /seismic_cal/runMPEM.r > /I-SUGAR-hob-0/runMPEM.out
