#
# Run calibration 4-Phen inference
#

# Use iydt/4-phen image containing required
# R packages, global functions, IYDT-specific
# functions and data, and phenomenology-specific
# functions
FROM iydt/4-phen

## source run file
CMD Rscript /4phen_cal/runMPEM.r > /I-SUGAR-hob-0/runMPEM.out
