#
# Run new event Acoustic inference
#

# Use iydt/acoustic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and acoustic-specific
# functions
FROM iydt/acoustic

## source run file
CMD Rscript /I-SUGAR-hob-0/runMPEM_0.r > /I-SUGAR-hob-0/runMPEM_0.out
