#
# Run calibration Optical inference
#

# Use iydt/optic image containing required
# R packages, global functions, IYDT-specific
# functions and data, and optical-specific
# functions
FROM iydt/optic

## source run file
CMD Rscript /optic_cal/runMPEM.r > /I-SUGAR-hob-0/runMPEM.out
