#
# Run new event 4-Phen inference
#

# Use iydt/4-phen image containing required
# R packages, global functions, IYDT-specific
# functions and data, and phenomenology-specific
# functions
FROM iydt/4-phen

## source run file
CMD Rscript /I-EIV-SUGAR-hob-pi-0/runMPEM_0.r > /I-EIV-SUGAR-hob-pi-0/runMPEM_0.out
